apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-auth
  namespace: kube-system
data:
  mapRoles: |
    - rolearn: arn:aws:iam::645437362580:role/default-eks-node-group-20260610092054058000000001
      username: system:node:{{EC2PrivateDNSName}}
      groups:
        - system:bootstrappers
        - system:nodes

    - rolearn: arn:aws:iam::645437362580:role/CodeBuildBrainRole
      username: codebuild
      groups:
        - system:masters
